/**
 * Database schema (Drizzle ORM, PostgreSQL).
 *
 * Conventions that hold for every table:
 *  - `id` is a uuid primary key generated by the database
 *  - `created_at` / `updated_at` are timestamptz and never null
 *  - deletion is soft (`deleted_at`), except for `sessions` and `email_tokens`
 *    which are genuinely disposable and must disappear when they expire
 */
import {
  boolean,
  date,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
  type AnyPgColumn,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

/* ------------------------------------------------------------------ */
/* Enums                                                               */
/* ------------------------------------------------------------------ */

/** Roles are ordered: every role includes the powers of the one before it. */
export const roleEnum = pgEnum("role", ["user", "writer", "editor", "admin"]);

export const writerStatusEnum = pgEnum("writer_status", [
  "pending_agreement",
  "active",
  "suspended",
]);

/**
 * The editor's duty state. Editors have no `writer_status`; suspension (a
 * freeze, by an admin or by the editor themself) is tracked separately so the
 * editor panel can be locked without touching their role.
 */
export const editorStatusEnum = pgEnum("editor_status", ["active", "suspended"]);

export const emailTokenTypeEnum = pgEnum("email_token_type", [
  "verify_email",
  "reset_password",
  "change_email",
]);

/**
 * Writer application pipeline (§6 of the writer-application module).
 *
 * The flow is strictly staged: the applicant does nothing after submitting, an
 * editor decides first, an admin decides second, and only the applicant's own
 * contract signature turns them into a writer.
 */
export const writerApplicationStatusEnum = pgEnum("writer_application_status", [
  "submitted", // waiting for the editor
  "editor_approved", // editor passed it on; waiting for the admin
  "admin_approved", // contract defined; waiting for the applicant to sign
  "signed", // applicant signed; the role change happened
  "editor_rejected",
  "admin_rejected",
]);

export const announcementAudienceEnum = pgEnum("announcement_audience", [
  "writers",
  "editors",
  "all_staff",
]);

/** How urgent an internal announcement is; critical ones force an acknowledgement. */
export const announcementSeverityEnum = pgEnum("announcement_severity", [
  "info",
  "important",
  "critical",
]);

export const issueStatusEnum = pgEnum("issue_status", [
  "planning",
  "in_production",
  "published",
  "archived",
]);

export const articleStatusEnum = pgEnum("article_status", [
  "draft",
  "in_review",
  "revision_requested",
  "accepted",
  "awaiting_rights",
  "scheduled",
  "published",
  "archived",
  "withdrawn",
]);

export const plagiarismStatusEnum = pgEnum("plagiarism_check_status", [
  "not_run",
  "clean",
  "flagged",
]);

export const grantTypeEnum = pgEnum("grant_type", [
  "assignment",
  "exclusive_license",
  "non_exclusive_license",
]);

export const grantStatusEnum = pgEnum("grant_status", ["pending", "signed", "declined", "revoked"]);

/** How the author is credited on a given work (§7, contract art. 7). */
export const bylineChoiceEnum = pgEnum("byline_choice", ["real_name", "pen_name"]);

/** Whether an edit stayed inside contract art. 6.2 or changed the work (§7.5). */
export const changeKindEnum = pgEnum("change_kind", ["correction", "content_change"]);

/** Only `none` for now; the column exists so a future paid model needs no change of meaning. */
export const considerationEnum = pgEnum("consideration", ["none"]);

export const licenseTypeEnum = pgEnum("license_type", [
  "own_work",
  "cc0",
  "cc_by",
  "stock_licensed",
  "permission_letter",
  "contract_pdf",
  "other",
]);

/** Rate limit buckets (see DECISIONS.md D-007). */
export const authScopeEnum = pgEnum("auth_scope", [
  "register_ip",
  "login_ip",
  "login_account",
  "login_2fa",
  "password_reset_ip",
]);

/* ------------------------------------------------------------------ */
/* Shared column builders                                              */
/* ------------------------------------------------------------------ */

const id = () => uuid("id").primaryKey().defaultRandom();
const createdAt = () => timestamp("created_at", { withTimezone: true }).notNull().defaultNow();
const updatedAt = () => timestamp("updated_at", { withTimezone: true }).notNull().defaultNow();
const deletedAt = () => timestamp("deleted_at", { withTimezone: true });

export type SocialLinks = {
  x?: string;
  instagram?: string;
  tiktok?: string;
  substack?: string;
};

/* ------------------------------------------------------------------ */
/* users                                                               */
/* ------------------------------------------------------------------ */

export const users = pgTable(
  "users",
  {
    id: id(),
    /** Always stored lowercase and trimmed; normalisation happens in the service layer. */
    email: text("email").notNull(),
    emailVerifiedAt: timestamp("email_verified_at", { withTimezone: true }),
    /**
     * The address a user is switching to, held here until the change link
     * sent to it is followed. Cleared once the swap happens.
     */
    pendingEmail: text("pending_email"),
    passwordHash: text("password_hash").notNull(),

    displayName: text("display_name").notNull(),
    /** Pen name (mahlas). This is what the public site shows when it is set. */
    penName: text("pen_name"),
    penNameSlug: text("pen_name_slug"),
    bio: text("bio"),
    avatarMediaId: uuid("avatar_media_id"),
    socialLinks: jsonb("social_links").$type<SocialLinks>(),

    /** Required before a promotion to writer; immutable for the user once set. */
    birthDate: date("birth_date"),

    /**
     * When the account was created through the public writer registration form
     * (/yazar-basvuru). Marks a "geçici yazar" candidate: the address is
     * verified by e-mail and the account is then auto-approved to writer — no
     * editor/admin review (D-049). Null for reader and staff accounts.
     */
    writerIntentAt: timestamp("writer_intent_at", { withTimezone: true }),

    /** The writing area the candidate chose at registration (D-051). */
    writerArea: text("writer_area"),

    role: roleEnum("role").notNull().default("user"),
    writerStatus: writerStatusEnum("writer_status"),
    /** Belongs to editors only; admins and writers leave it null (D-039). */
    editorStatus: editorStatusEnum("editor_status"),

    kvkkConsentAt: timestamp("kvkk_consent_at", { withTimezone: true }),
    kvkkConsentVersion: integer("kvkk_consent_version"),

    /**
     * TOTP second factor (D-048). The secret is AES-GCM encrypted with the
     * session pepper, so a database dump alone yields nothing; `totpEnabledAt`
     * is null until the code was verified once.
     */
    totpSecret: text("totp_secret"),
    totpEnabledAt: timestamp("totp_enabled_at", { withTimezone: true }),

    isBanned: boolean("is_banned").notNull().default(false),
    bannedReason: text("banned_reason"),

    /** Self-service deletion request; the account is soft deleted 30 days later. */
    deletionRequestedAt: timestamp("deletion_requested_at", { withTimezone: true }),
    anonymizedAt: timestamp("anonymized_at", { withTimezone: true }),

    createdAt: createdAt(),
    updatedAt: updatedAt(),
    deletedAt: deletedAt(),
  },
  (t) => [
    // Partial unique index: a deleted account must not reserve its e-mail forever (D-014)
    uniqueIndex("users_email_unique").on(t.email).where(sql`${t.deletedAt} is null`),
    uniqueIndex("users_pen_name_slug_unique")
      .on(t.penNameSlug)
      .where(sql`${t.deletedAt} is null and ${t.penNameSlug} is not null`),
    index("users_role_idx").on(t.role),
  ],
);

/* ------------------------------------------------------------------ */
/* writer_applications                                                 */
/* ------------------------------------------------------------------ */

export const writerApplications = pgTable(
  "writer_applications",
  {
    id: id(),
    /** Who applied. Null once the account is anonymised. */
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "set null" }),
    status: writerApplicationStatusEnum("status").notNull().default("submitted"),
    /** The uploaded sample work. Stored in the media bucket, never public. */
    sampleMediaId: uuid("sample_media_id").references(() => media.id, { onDelete: "set null" }),
    /** The applicant's own words about their sample work. */
    note: text("note"),
    /** The latest reviewer's note; set by whichever reviewer decided last. */
    reviewNote: text("review_note"),
    submittedAt: timestamp("submitted_at", { withTimezone: true }).notNull().defaultNow(),
    editorBy: uuid("editor_by").references(() => users.id, { onDelete: "set null" }),
    editorReviewedAt: timestamp("editor_reviewed_at", { withTimezone: true }),
    adminBy: uuid("admin_by").references(() => users.id, { onDelete: "set null" }),
    adminReviewedAt: timestamp("admin_reviewed_at", { withTimezone: true }),
    /** The contract assigned at admin approval; the applicant signs it last. */
    contractVersionId: uuid("contract_version_id").references(() => agreementVersions.id, {
      onDelete: "set null",
    }),
    signedAt: timestamp("signed_at", { withTimezone: true }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    // Cooldown and "my applications" lookups: one row per user, newest first
    index("writer_applications_user_idx").on(t.userId, t.submittedAt),
    index("writer_applications_status_idx").on(t.status),
    // At most one application may be mid-flight per user; finished ones stay
    // as history and the service enforces the 30 day cooldown on top of this
    uniqueIndex("writer_applications_one_open")
      .on(t.userId)
      .where(
        sql`${t.status} in ('submitted', 'editor_approved', 'admin_approved')`,
      ),
  ],
);

/* ------------------------------------------------------------------ */
/* sessions                                                            */
/* ------------------------------------------------------------------ */

export const sessions = pgTable(
  "sessions",
  {
    id: id(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    /** sha256(token + SESSION_SECRET); the raw token only ever lives in the cookie. */
    tokenHash: text("token_hash").notNull(),
    ip: text("ip"),
    userAgent: text("user_agent"),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    lastSeenAt: timestamp("last_seen_at", { withTimezone: true }).notNull().defaultNow(),
    revokedAt: timestamp("revoked_at", { withTimezone: true }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    uniqueIndex("sessions_token_hash_unique").on(t.tokenHash),
    index("sessions_user_id_idx").on(t.userId),
    index("sessions_expires_at_idx").on(t.expiresAt),
  ],
);

/* ------------------------------------------------------------------ */
/* email_tokens                                                        */
/* ------------------------------------------------------------------ */

export const emailTokens = pgTable(
  "email_tokens",
  {
    id: id(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    type: emailTokenTypeEnum("type").notNull(),
    tokenHash: text("token_hash").notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    usedAt: timestamp("used_at", { withTimezone: true }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    uniqueIndex("email_tokens_token_hash_unique").on(t.tokenHash),
    index("email_tokens_user_type_idx").on(t.userId, t.type),
  ],
);

/* ------------------------------------------------------------------ */
/* login_challenges (two-factor step, D-048)                           */
/* ------------------------------------------------------------------ */

/**
 * A single-use ticket issued after the password half of a two-factor login.
 * Carries no secrets itself: only the peppered hash is stored, and the row
 * dies five minutes after it was issued.
 */
export const loginChallenges = pgTable(
  "login_challenges",
  {
    id: id(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    tokenHash: text("token_hash").notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    consumedAt: timestamp("consumed_at", { withTimezone: true }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    uniqueIndex("login_challenges_token_hash_unique").on(t.tokenHash),
    index("login_challenges_user_idx").on(t.userId),
    index("login_challenges_expires_at_idx").on(t.expiresAt),
  ],
);

/* ------------------------------------------------------------------ */
/* auth_attempts (rate limiting, D-007)                                */
/* ------------------------------------------------------------------ */

export const authAttempts = pgTable(
  "auth_attempts",
  {
    id: id(),
    scope: authScopeEnum("scope").notNull(),
    /** IP address or lowercased e-mail, depending on the scope. */
    identifier: text("identifier").notNull(),
    count: integer("count").notNull().default(0),
    /** Set while the bucket is locked out; requests are rejected until it passes. */
    lockedUntil: timestamp("locked_until", { withTimezone: true }),
    windowStartedAt: timestamp("window_started_at", { withTimezone: true }).notNull().defaultNow(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [uniqueIndex("auth_attempts_scope_identifier_unique").on(t.scope, t.identifier)],
);

/* ------------------------------------------------------------------ */
/* role_changes (append only, D-015)                                   */
/* ------------------------------------------------------------------ */

export const roleChanges = pgTable(
  "role_changes",
  {
    id: id(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),
    oldRole: roleEnum("old_role").notNull(),
    newRole: roleEnum("new_role").notNull(),
    changedBy: uuid("changed_by").references(() => users.id, { onDelete: "restrict" }),
    note: text("note"),
    createdAt: createdAt(),
  },
  (t) => [index("role_changes_user_idx").on(t.userId)],
);

/* ------------------------------------------------------------------ */
/* media                                                               */
/* ------------------------------------------------------------------ */

export const media = pgTable(
  "media",
  {
    id: id(),
    storageKey: text("storage_key").notNull(),
    mime: text("mime").notNull(),
    size: integer("size").notNull(),
    width: integer("width"),
    height: integer("height"),
    uploadedBy: uuid("uploaded_by").references(() => users.id, { onDelete: "set null" }),

    /** A media row without a license type can never be attached to an article. */
    licenseType: licenseTypeEnum("license_type"),
    licenseSource: text("license_source"),
    licenseEvidenceMediaId: uuid("license_evidence_media_id"),
    altText: text("alt_text"),

    createdAt: createdAt(),
    updatedAt: updatedAt(),
    deletedAt: deletedAt(),
  },
  (t) => [index("media_uploaded_by_idx").on(t.uploadedBy)],
);

/* ------------------------------------------------------------------ */
/* agreement_versions / agreement_acceptances                          */
/* ------------------------------------------------------------------ */

export const agreementVersions = pgTable(
  "agreement_versions",
  {
    id: id(),
    version: integer("version").notNull(),
    title: text("title").notNull(),
    bodyMarkdown: text("body_markdown").notNull(),
    /** sha256 of the exact body text that was published. */
    bodyHash: text("body_hash").notNull(),
    pdfMediaId: uuid("pdf_media_id").references(() => media.id, { onDelete: "set null" }),
    publishedAt: timestamp("published_at", { withTimezone: true }),
    publishedBy: uuid("published_by").references(() => users.id, { onDelete: "set null" }),
    isCurrent: boolean("is_current").notNull().default(false),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
    deletedAt: deletedAt(),
  },
  (t) => [
    uniqueIndex("agreement_versions_version_unique").on(t.version),
    // At most one current version at any time, enforced by the database
    uniqueIndex("agreement_versions_single_current").on(t.isCurrent).where(sql`${t.isCurrent}`),
  ],
);

export const agreementAcceptances = pgTable(
  "agreement_acceptances",
  {
    id: id(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),
    agreementVersionId: uuid("agreement_version_id")
      .notNull()
      .references(() => agreementVersions.id, { onDelete: "restrict" }),
    acceptedAt: timestamp("accepted_at", { withTimezone: true }).notNull().defaultNow(),
    ip: text("ip"),
    userAgent: text("user_agent"),
    /** Hash of the text actually shown to the user at acceptance time. */
    bodyHashAtAcceptance: text("body_hash_at_acceptance").notNull(),
    /**
     * The contract exactly as it was shown, placeholders filled (§4). This is
     * the evidence; the PDF is only a readable copy of it.
     */
    renderedMarkdown: text("rendered_markdown"),
    pdfMediaId: uuid("pdf_media_id").references(() => media.id, { onDelete: "set null" }),
    /** Filled in when a newer version is published; the row is never deleted. */
    supersededAt: timestamp("superseded_at", { withTimezone: true }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    uniqueIndex("agreement_acceptances_user_version_unique").on(t.userId, t.agreementVersionId),
  ],
);

/* ------------------------------------------------------------------ */
/* announcements                                                       */
/* ------------------------------------------------------------------ */

export const announcements = pgTable(
  "announcements",
  {
    id: id(),
    title: text("title").notNull(),
    bodyMarkdown: text("body_markdown").notNull(),
    audience: announcementAudienceEnum("audience").notNull(),
    severity: announcementSeverityEnum("severity").notNull().default("info"),
    requiresAcknowledgement: boolean("requires_acknowledgement").notNull().default(false),
    publishedAt: timestamp("published_at", { withTimezone: true }),
    publishedBy: uuid("published_by").references(() => users.id, { onDelete: "set null" }),
    pinned: boolean("pinned").notNull().default(false),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
    deletedAt: deletedAt(),
  },
  (t) => [index("announcements_published_at_idx").on(t.publishedAt)],
);

export const announcementReads = pgTable(
  "announcement_reads",
  {
    id: id(),
    announcementId: uuid("announcement_id")
      .notNull()
      .references(() => announcements.id, { onDelete: "cascade" }),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    readAt: timestamp("read_at", { withTimezone: true }).notNull().defaultNow(),
    acknowledgedAt: timestamp("acknowledged_at", { withTimezone: true }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [uniqueIndex("announcement_reads_unique").on(t.announcementId, t.userId)],
);

/* ------------------------------------------------------------------ */
/* issues                                                              */
/* ------------------------------------------------------------------ */

export const issues = pgTable(
  "issues",
  {
    id: id(),
    number: integer("number").notNull(),
    title: text("title").notNull(),
    theme: text("theme"),
    coverMediaId: uuid("cover_media_id").references(() => media.id, { onDelete: "set null" }),
    status: issueStatusEnum("status").notNull().default("planning"),
    plannedPublishDate: date("planned_publish_date"),
    publishedAt: timestamp("published_at", { withTimezone: true }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
    deletedAt: deletedAt(),
  },
  (t) => [uniqueIndex("issues_number_unique").on(t.number).where(sql`${t.deletedAt} is null`)],
);

/* ------------------------------------------------------------------ */
/* articles                                                            */
/* ------------------------------------------------------------------ */

export const articles = pgTable(
  "articles",
  {
    id: id(),
    issueId: uuid("issue_id").references(() => issues.id, { onDelete: "set null" }),
    title: text("title").notNull(),
    slug: text("slug").notNull(),
    summary: text("summary"),
    /** Pasted in by an editor; there is no writer-facing submission flow in this phase. */
    bodyMarkdown: text("body_markdown").notNull().default(""),

    authorId: uuid("author_id").references(() => users.id, { onDelete: "restrict" }),

    category: text("category"),
    tags: text("tags")
      .array()
      .notNull()
      .default(sql`'{}'::text[]`),

    status: articleStatusEnum("status").notNull().default("draft"),

    dueDate: date("due_date"),
    scheduledAt: timestamp("scheduled_at", { withTimezone: true }),
    publishedAt: timestamp("published_at", { withTimezone: true }),
    withdrawnAt: timestamp("withdrawn_at", { withTimezone: true }),
    withdrawnReason: text("withdrawn_reason"),

    orderInIssue: integer("order_in_issue"),

    plagiarismCheckStatus: plagiarismStatusEnum("plagiarism_check_status")
      .notNull()
      .default("not_run"),
    plagiarismNote: text("plagiarism_note"),

    createdAt: createdAt(),
    updatedAt: updatedAt(),
    deletedAt: deletedAt(),
  },
  (t) => [
    uniqueIndex("articles_slug_unique").on(t.slug).where(sql`${t.deletedAt} is null`),
    index("articles_status_idx").on(t.status),
    index("articles_issue_idx").on(t.issueId),
    index("articles_author_idx").on(t.authorId),
    index("articles_scheduled_at_idx").on(t.scheduledAt),
  ],
);

export const articleVersions = pgTable(
  "article_versions",
  {
    id: id(),
    articleId: uuid("article_id")
      .notNull()
      .references(() => articles.id, { onDelete: "cascade" }),
    version: integer("version").notNull(),
    bodyMarkdown: text("body_markdown").notNull(),
    changedBy: uuid("changed_by").references(() => users.id, { onDelete: "set null" }),
    changeNote: text("change_note"),
    /** A content change revokes the work approval; a correction keeps it (§7.5). */
    changeKind: changeKindEnum("change_kind").notNull().default("correction"),
    /** Marks the snapshot taken at the moment the article went public. */
    isPublishedSnapshot: boolean("is_published_snapshot").notNull().default(false),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [uniqueIndex("article_versions_article_version_unique").on(t.articleId, t.version)],
);

export const articleComments = pgTable(
  "article_comments",
  {
    id: id(),
    articleId: uuid("article_id")
      .notNull()
      .references(() => articles.id, { onDelete: "cascade" }),
    authorId: uuid("author_id").references(() => users.id, { onDelete: "set null" }),
    body: text("body").notNull(),
    resolvedAt: timestamp("resolved_at", { withTimezone: true }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
    deletedAt: deletedAt(),
  },
  (t) => [index("article_comments_article_idx").on(t.articleId)],
);

/** Which media a given article uses; license completeness is checked over this join. */
export const articleMedia = pgTable(
  "article_media",
  {
    id: id(),
    articleId: uuid("article_id")
      .notNull()
      .references(() => articles.id, { onDelete: "cascade" }),
    mediaId: uuid("media_id")
      .notNull()
      .references(() => media.id, { onDelete: "restrict" }),
    role: text("role").notNull().default("inline"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [uniqueIndex("article_media_unique").on(t.articleId, t.mediaId)],
);

/* ------------------------------------------------------------------ */
/* rights_grants                                                       */
/* ------------------------------------------------------------------ */

export const rightsGrants = pgTable(
  "rights_grants",
  {
    id: id(),
    articleId: uuid("article_id")
      .notNull()
      .references(() => articles.id, { onDelete: "cascade" }),
    grantorId: uuid("grantor_id")
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),

    /** The contract version whose article 4 fixes this licence's scope (§7.1). */
    agreementVersionId: uuid("agreement_version_id").references(() => agreementVersions.id, {
      onDelete: "restrict",
    }),
    bylineChoice: bylineChoiceEnum("byline_choice"),

    grantType: grantTypeEnum("grant_type").notNull(),

    // FSEK requires each economic right to be listed one by one (art. 52)
    rightAdaptation: boolean("right_adaptation").notNull().default(false), // m.21 işleme
    rightReproduction: boolean("right_reproduction").notNull().default(false), // m.22 çoğaltma
    rightDistribution: boolean("right_distribution").notNull().default(false), // m.23 yayma
    rightCommunicationToPublic: boolean("right_communication_to_public").notNull().default(false), // m.25 umuma iletim

    channels: text("channels")
      .array()
      .notNull()
      .default(sql`'{}'::text[]`),
    exclusivityMonths: integer("exclusivity_months"),
    territory: text("territory").notNull().default("worldwide"),
    consideration: considerationEnum("consideration").notNull().default("none"),
    commercialUseIncluded: boolean("commercial_use_included").notNull().default(false),

    /** sha256 of the full form text that was rendered to the writer. */
    formTextHash: text("form_text_hash").notNull(),
    formPdfMediaId: uuid("form_pdf_media_id").references(() => media.id, { onDelete: "set null" }),

    status: grantStatusEnum("status").notNull().default("pending"),
    signedAt: timestamp("signed_at", { withTimezone: true }),
    signedIp: text("signed_ip"),
    signedUserAgent: text("signed_user_agent"),
    declinedAt: timestamp("declined_at", { withTimezone: true }),
    declinedReason: text("declined_reason"),
    revokedAt: timestamp("revoked_at", { withTimezone: true }),
    revokedBy: uuid("revoked_by").references(() => users.id, { onDelete: "set null" }),
    /** Set when the writer was last nudged, so reminders do not repeat daily. */
    reminderSentAt: timestamp("reminder_sent_at", { withTimezone: true }),

    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    // One live approval per article; revoked and declined ones stay as history
    uniqueIndex("rights_grants_article_active_unique")
      .on(t.articleId)
      .where(sql`${t.status} in ('pending', 'signed')`),
    index("rights_grants_grantor_idx").on(t.grantorId),
    index("rights_grants_status_idx").on(t.status),
  ],
);

/* ------------------------------------------------------------------ */
/* kvkk_versions                                                       */
/* ------------------------------------------------------------------ */

export const kvkkVersions = pgTable(
  "kvkk_versions",
  {
    id: id(),
    version: integer("version").notNull(),
    title: text("title").notNull(),
    bodyMarkdown: text("body_markdown").notNull(),
    bodyHash: text("body_hash").notNull(),
    publishedAt: timestamp("published_at", { withTimezone: true }),
    publishedBy: uuid("published_by").references(() => users.id, { onDelete: "set null" }),
    isCurrent: boolean("is_current").notNull().default(false),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    uniqueIndex("kvkk_versions_version_unique").on(t.version),
    uniqueIndex("kvkk_versions_single_current").on(t.isCurrent).where(sql`${t.isCurrent}`),
  ],
);

/* ------------------------------------------------------------------ */
/* site_settings (publisher details for the contract, §3)              */

/* ------------------------------------------------------------------ */

/**
 * Values the contract template needs but the database cannot infer: who the
 * publishing partners are, the notification address, the jurisdiction. Only an
 * admin edits them and every change lands in the audit log.
 */
export const siteSettings = pgTable("site_settings", {
  key: text("key").primaryKey(),
  value: text("value").notNull(),
  updatedBy: uuid("updated_by").references(() => users.id, { onDelete: "set null" }),
  createdAt: createdAt(),
  updatedAt: updatedAt(),
});

/* ------------------------------------------------------------------ */
/* notifications (in-panel, D-008)                                     */
/* ------------------------------------------------------------------ */

export const notifications = pgTable(
  "notifications",
  {
    id: id(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    kind: text("kind").notNull(),
    title: text("title").notNull(),
    body: text("body"),
    href: text("href"),
    readAt: timestamp("read_at", { withTimezone: true }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [index("notifications_user_idx").on(t.userId, t.readAt)],
);

/* ------------------------------------------------------------------ */
/* community (blog comments, chat, banned words)                       */
/* ------------------------------------------------------------------ */

/**
 * The moderation blacklist (module 4). Words are stored normalized (lowercase,
 * Turkish locale) and matched case-insensitively as substrings, so suffixed
 * forms are covered too. Removal is a soft delete so an admin can restore.
 */
export const bannedWords = pgTable(
  "banned_words",
  {
    id: id(),
    word: text("word").notNull(),
    createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
    deletedAt: deletedAt(),
  },
  (t) => [
    // A live word is unique; soft-deleted ones stay as history
    uniqueIndex("banned_words_word_unique").on(t.word).where(sql`${t.deletedAt} is null`),
  ],
);

/** A reader's comment on a published magazine article. */
export const communityComments = pgTable(
  "community_comments",
  {
    id: id(),
    articleId: uuid("article_id")
      .notNull()
      .references(() => articles.id, { onDelete: "cascade" }),
    authorId: uuid("author_id").references(() => users.id, { onDelete: "set null" }),
    /** The comment with banned words already masked (module 4). */
    body: text("body").notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
    deletedAt: deletedAt(),
  },
  (t) => [
    index("community_comments_article_idx").on(t.articleId, t.createdAt),
  ],
);

/** A message in the community chat; an optional quote references another one. */
export const communityMessages = pgTable(
  "community_messages",
  {
    id: id(),
    authorId: uuid("author_id").references(() => users.id, { onDelete: "set null" }),
    body: text("body").notNull(),
    // Self reference: the explicit return type breaks the circular inference
    quotedMessageId: uuid("quoted_message_id").references(
      (): AnyPgColumn => communityMessages.id,
      { onDelete: "set null" },
    ),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
    deletedAt: deletedAt(),
  },
  (t) => [index("community_messages_created_idx").on(t.createdAt)],
);

/* ------------------------------------------------------------------ */
/* audit_log (append only, D-015)                                      */
/* ------------------------------------------------------------------ */

export const auditLog = pgTable(
  "audit_log",
  {
    id: id(),
    /** Null for actions performed by scheduled jobs rather than a person. */
    actorId: uuid("actor_id").references(() => users.id, { onDelete: "set null" }),
    action: text("action").notNull(),
    entityType: text("entity_type").notNull(),
    entityId: uuid("entity_id"),
    before: jsonb("before"),
    after: jsonb("after"),
    ip: text("ip"),
    createdAt: createdAt(),
  },
  (t) => [
    index("audit_log_entity_idx").on(t.entityType, t.entityId),
    index("audit_log_created_at_idx").on(t.createdAt),
    index("audit_log_actor_idx").on(t.actorId),
  ],
);

/* ------------------------------------------------------------------ */
/* Inferred types                                                      */
/* ------------------------------------------------------------------ */

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
export type Session = typeof sessions.$inferSelect;
export type Article = typeof articles.$inferSelect;
export type Issue = typeof issues.$inferSelect;
export type RightsGrant = typeof rightsGrants.$inferSelect;
export type WriterApplication = typeof writerApplications.$inferSelect;
export type MediaRow = typeof media.$inferSelect;
export type CommunityComment = typeof communityComments.$inferSelect;
export type CommunityMessage = typeof communityMessages.$inferSelect;
export type BannedWord = typeof bannedWords.$inferSelect;
export type AgreementVersion = typeof agreementVersions.$inferSelect;
export type Announcement = typeof announcements.$inferSelect;
export type AnnouncementSeverity = (typeof announcementSeverityEnum.enumValues)[number];
export type Role = (typeof roleEnum.enumValues)[number];
export type ArticleStatus = (typeof articleStatusEnum.enumValues)[number];
export type WriterStatus = (typeof writerStatusEnum.enumValues)[number];
export type EditorStatus = (typeof editorStatusEnum.enumValues)[number];
export type GrantStatus = (typeof grantStatusEnum.enumValues)[number];
export type WriterApplicationStatus = (typeof writerApplicationStatusEnum.enumValues)[number];
export type LicenseType = (typeof licenseTypeEnum.enumValues)[number];
