/**
 * Database schema (Drizzle ORM, PostgreSQL).
 *
 * Conventions that hold for every table:
 *  - `id` is a uuid primary key generated by the database
 *  - `created_at` / `updated_at` are timestamptz and never null
 *  - deletion is soft (`deleted_at`), except for `sessions` and `email_tokens`
 *    which are genuinely disposable and must disappear when they expire
 */
import {
  boolean,
  check,
  date,
  doublePrecision,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
  type AnyPgColumn,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

/* ------------------------------------------------------------------ */
/* Enums                                                               */
/* ------------------------------------------------------------------ */

/** Roles are ordered: every role includes the powers of the one before it. */
export const roleEnum = pgEnum("role", ["user", "writer", "editor", "admin"]);

/** Who may start a private conversation with a member (D-091). */
export const dmPolicyEnum = pgEnum("dm_policy", ["everyone", "following", "nobody"]);

export const writerStatusEnum = pgEnum("writer_status", [
  "pending_agreement",
  "active",
  "suspended",
]);

/**
 * The editor's duty state. Editors have no `writer_status`; suspension (a
 * freeze, by an admin or by the editor themself) is tracked separately so the
 * editor panel can be locked without touching their role.
 */
export const editorStatusEnum = pgEnum("editor_status", ["active", "suspended"]);

export const emailTokenTypeEnum = pgEnum("email_token_type", [
  "verify_email",
  "reset_password",
  "change_email",
]);

/**
 * Writer application pipeline (§6 of the writer-application module).
 *
 * The flow is strictly staged: the applicant does nothing after submitting, an
 * editor decides first, an admin decides second, and only the applicant's own
 * contract signature turns them into a writer.
 */
export const writerApplicationStatusEnum = pgEnum("writer_application_status", [
  "submitted", // waiting for the editor
  "editor_approved", // editor passed it on; waiting for the admin
  "admin_approved", // contract defined; waiting for the applicant to sign
  "signed", // applicant signed; the role change happened
  "editor_rejected",
  "admin_rejected",
]);

export const announcementAudienceEnum = pgEnum("announcement_audience", [
  "writers",
  "editors",
  "all_staff",
]);

/** How urgent an internal announcement is; critical ones force an acknowledgement. */
export const announcementSeverityEnum = pgEnum("announcement_severity", [
  "info",
  "important",
  "critical",
]);

export const issueStatusEnum = pgEnum("issue_status", [
  "planning",
  "in_production",
  "published",
  "archived",
]);

/**
 * The editorial chain is staged (D-059): a draft reaches the category editor
 * (`in_review`), their approval hands it to the main editor
 * (`pending_admin_approval`), and the main editor's approval drops it into the
 * admin's publication queue (`ready_for_publishing`). `accepted` and everything
 * after it belong to the admin/publication flow. The two review-stage names
 * follow the product's hierarchy (D-068).
 */
export const articleStatusEnum = pgEnum("article_status", [
  "draft",
  "in_review",
  "pending_admin_approval",
  "ready_for_publishing",
  "revision_requested",
  "accepted",
  "awaiting_rights",
  "scheduled",
  "published",
  "archived",
  "withdrawn",
]);

export const plagiarismStatusEnum = pgEnum("plagiarism_check_status", [
  "not_run",
  "clean",
  "flagged",
]);

export const grantTypeEnum = pgEnum("grant_type", [
  "assignment",
  "exclusive_license",
  "non_exclusive_license",
]);

export const grantStatusEnum = pgEnum("grant_status", ["pending", "signed", "declined", "revoked"]);

/** How the author is credited on a given work (§7, contract art. 7). */
export const bylineChoiceEnum = pgEnum("byline_choice", ["real_name", "pen_name"]);

/**
 * The page layouts an issue is built from (D-234). Labels and the fields each
 * one asks for live in `src/lib/issue-templates.ts`; this list only fixes the
 * stored values.
 */
export const pageTemplateEnum = pgEnum("page_template", [
  "cover",
  "masthead",
  "editorial",
  "contents",
  "theme_opening",
  "section_opening",
  "article_opening",
  "article_continued",
  "visual_article",
  "collage_opening",
  "full_bleed",
  "picks",
  "playlist",
  "interactive",
  "ps_closing",
  "back_cover",
]);

/** What a clickable area on a page image does when a reader chooses it (D-240). */
export const hotspotKindEnum = pgEnum("hotspot_kind", ["link", "page", "info", "quiz"]);

/**
 * The two kinds of quiz (D-240): one with a right answer per question, one
 * that adds points up and names an outcome for the band the total falls in.
 */
export const quizKindEnum = pgEnum("quiz_kind", ["knowledge", "scored"]);

/** The twelve signs, for the team form (D-226); labels live in `src/lib/zodiac.ts`. */
export const zodiacEnum = pgEnum("zodiac", [
  "aries",
  "taurus",
  "gemini",
  "cancer",
  "leo",
  "virgo",
  "libra",
  "scorpio",
  "sagittarius",
  "capricorn",
  "aquarius",
  "pisces",
]);

/** Whether an edit stayed inside contract art. 6.2 or changed the work (§7.5). */
export const changeKindEnum = pgEnum("change_kind", ["correction", "content_change"]);

/** Only `none` for now; the column exists so a future paid model needs no change of meaning. */
export const considerationEnum = pgEnum("consideration", ["none"]);

export const licenseTypeEnum = pgEnum("license_type", [
  "own_work",
  "cc0",
  "cc_by",
  "stock_licensed",
  "permission_letter",
  "contract_pdf",
  "other",
]);

/** Rate limit buckets (see DECISIONS.md D-007). */
export const authScopeEnum = pgEnum("auth_scope", [
  "register_ip",
  "login_ip",
  "login_account",
  "login_2fa",
  "password_reset_ip",
  /** The contact form, counted per IP address (D-145). */
  "contact_form_ip",
]);

/* ------------------------------------------------------------------ */
/* Shared column builders                                              */
/* ------------------------------------------------------------------ */

const id = () => uuid("id").primaryKey().defaultRandom();
const createdAt = () => timestamp("created_at", { withTimezone: true }).notNull().defaultNow();
const updatedAt = () => timestamp("updated_at", { withTimezone: true }).notNull().defaultNow();
const deletedAt = () => timestamp("deleted_at", { withTimezone: true });

export type SocialLinks = {
  x?: string;
  instagram?: string;
  tiktok?: string;
  substack?: string;
};

/* ------------------------------------------------------------------ */
/* users                                                               */
/* ------------------------------------------------------------------ */

export const users = pgTable(
  "users",
  {
    id: id(),
    /** Always stored lowercase and trimmed; normalisation happens in the service layer. */
    email: text("email").notNull(),
    emailVerifiedAt: timestamp("email_verified_at", { withTimezone: true }),
    /**
     * The address a user is switching to, held here until the change link
     * sent to it is followed. Cleared once the swap happens.
     */
    pendingEmail: text("pending_email"),
    passwordHash: text("password_hash").notNull(),

    displayName: text("display_name").notNull(),
    /**
     * Pen name (mahlas). The magazine's name for the member: published work,
     * the imprint and the author page. Not shown in the community (D-163).
     */
    penName: text("pen_name"),
    penNameSlug: text("pen_name_slug"),
    /**
     * The community handle (D-089): lowercase, stored normalised. Null until
     * the member opts into the social layer; nothing social works without it.
     */
    username: text("username"),
    /**
     * The name the community shows in place of the handle (D-163), X's "Name".
     * Free text, not unique, never an address; without one the handle shows.
     */
    nickname: text("nickname"),
    /** Defaults to the people the member follows: nobody is reachable by strangers unasked. */
    dmPolicy: dmPolicyEnum("dm_policy").notNull().default("following"),
    /**
     * Read ticks both ways (D-188): off, the member's reading is not shown and
     * they see nobody else's. On by default, as the ticks were before.
     */
    readReceipts: boolean("read_receipts").notNull().default(true),
    /** The anonymous box is opt-in (D-092): closed until the member opens it. */
    anonBoxEnabled: boolean("anon_box_enabled").notNull().default(false),
    bio: text("bio"),
    /** The chips the settings design draws; ids from src/lib/interests.ts (D-149). */
    interests: text("interests").array(),
    avatarMediaId: uuid("avatar_media_id"),
    /** The cover photo across the top of the community profile (D-141). */
    headerMediaId: uuid("header_media_id"),
    socialLinks: jsonb("social_links").$type<SocialLinks>(),

    /**
     * Collected at registration; required before a promotion to writer and
     * immutable for the user once set.
     */
    birthDate: date("birth_date"),

    /**
     * When the account was created through the public writer registration form
     * (/yazar-basvuru). Marks a "geçici yazar" candidate: the address is
     * verified by e-mail and the account is then auto-approved to writer — no
     * editor/admin review (D-049). Null for reader and staff accounts.
     */
    writerIntentAt: timestamp("writer_intent_at", { withTimezone: true }),

    /** The writing area the candidate chose at registration (D-051). */
    writerArea: text("writer_area"),

    /**
     * An optional second area, assigned only from the admin panel (D-057).
     * The writer holds at most two areas; the value is a `writer_areas` name,
     * kept in step with a rename exactly like `writer_area`.
     */
    writerArea2: text("writer_area_2"),

    /** Contact number collected at writer registration; stored compact (D-053). */
    phone: text("phone"),

    role: roleEnum("role").notNull().default("user"),

    /**
     * Marks an account as an illustrator (D-151). Deliberately not a role: the
     * magazine has people who write and draw alike, and `role` holds one
     * value. The mark grants no panel of its own.
     */
    isIllustrator: boolean("is_illustrator").notNull().default(false),
    /**
     * Marks the magazine's legal adviser (D-238). Same idea as the illustrator
     * mark: not a role, grants no panel and no authority over content. It only
     * names the duty and opens the team avatar builder.
     */
    isLegalAdvisor: boolean("is_legal_advisor").notNull().default(false),
    /**
     * Marks an assistant working for the magazine (D-239). Same family as the
     * illustrator and legal adviser marks: not a role, no panel, no authority
     * over content — it names the duty and opens the team avatar builder.
     */
    isAssistant: boolean("is_assistant").notNull().default(false),
    writerStatus: writerStatusEnum("writer_status"),
    /** Belongs to editors only; admins and writers leave it null (D-039). */
    editorStatus: editorStatusEnum("editor_status"),
    /**
     * A main editor reads every category and approves the second review stage;
     * a plain editor only sees the categories assigned in `editor_categories`
     * and approves the first stage (D-059).
     */
    isMainEditor: boolean("is_main_editor").notNull().default(false),

    kvkkConsentAt: timestamp("kvkk_consent_at", { withTimezone: true }),
    kvkkConsentVersion: integer("kvkk_consent_version"),

    /**
     * TOTP second factor (D-048). The secret is AES-GCM encrypted with the
     * session pepper, so a database dump alone yields nothing; `totpEnabledAt`
     * is null until the code was verified once.
     */
    totpSecret: text("totp_secret"),
    totpEnabledAt: timestamp("totp_enabled_at", { withTimezone: true }),

    isBanned: boolean("is_banned").notNull().default(false),
    bannedReason: text("banned_reason"),

    /** Self-service deletion request; the account is soft deleted 30 days later. */
    deletionRequestedAt: timestamp("deletion_requested_at", { withTimezone: true }),
    anonymizedAt: timestamp("anonymized_at", { withTimezone: true }),

    createdAt: createdAt(),
    updatedAt: updatedAt(),
    deletedAt: deletedAt(),
  },
  (t) => [
    // Partial unique index: a deleted account must not reserve its e-mail forever (D-014)
    uniqueIndex("users_email_unique").on(t.email).where(sql`${t.deletedAt} is null`),
    uniqueIndex("users_pen_name_slug_unique")
      .on(t.penNameSlug)
      .where(sql`${t.deletedAt} is null and ${t.penNameSlug} is not null`),
    uniqueIndex("users_username_unique")
      .on(t.username)
      .where(sql`${t.deletedAt} is null and ${t.username} is not null`),
    index("users_role_idx").on(t.role),
  ],
);

/* ------------------------------------------------------------------ */
/* writer_applications                                                 */
/* ------------------------------------------------------------------ */

export const writerApplications = pgTable(
  "writer_applications",
  {
    id: id(),
    /** Who applied. Null once the account is anonymised. */
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "set null" }),
    status: writerApplicationStatusEnum("status").notNull().default("submitted"),
    /** The uploaded sample work. Stored in the media bucket, never public. */
    sampleMediaId: uuid("sample_media_id").references(() => media.id, { onDelete: "set null" }),
    /** The applicant's own words about their sample work. */
    note: text("note"),
    /** The latest reviewer's note; set by whichever reviewer decided last. */
    reviewNote: text("review_note"),
    submittedAt: timestamp("submitted_at", { withTimezone: true }).notNull().defaultNow(),
    editorBy: uuid("editor_by").references(() => users.id, { onDelete: "set null" }),
    editorReviewedAt: timestamp("editor_reviewed_at", { withTimezone: true }),
    adminBy: uuid("admin_by").references(() => users.id, { onDelete: "set null" }),
    adminReviewedAt: timestamp("admin_reviewed_at", { withTimezone: true }),
    /** The contract assigned at admin approval; the applicant signs it last. */
    contractVersionId: uuid("contract_version_id").references(() => agreementVersions.id, {
      onDelete: "set null",
    }),
    signedAt: timestamp("signed_at", { withTimezone: true }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    // Cooldown and "my applications" lookups: one row per user, newest first
    index("writer_applications_user_idx").on(t.userId, t.submittedAt),
    index("writer_applications_status_idx").on(t.status),
    // At most one application may be mid-flight per user; finished ones stay
    // as history and the service enforces the 30 day cooldown on top of this
    uniqueIndex("writer_applications_one_open")
      .on(t.userId)
      .where(
        sql`${t.status} in ('submitted', 'editor_approved', 'admin_approved')`,
      ),
  ],
);

/* ------------------------------------------------------------------ */
/* sessions                                                            */
/* ------------------------------------------------------------------ */

export const sessions = pgTable(
  "sessions",
  {
    id: id(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    /** sha256(token + SESSION_SECRET); the raw token only ever lives in the cookie. */
    tokenHash: text("token_hash").notNull(),
    ip: text("ip"),
    userAgent: text("user_agent"),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    lastSeenAt: timestamp("last_seen_at", { withTimezone: true }).notNull().defaultNow(),
    revokedAt: timestamp("revoked_at", { withTimezone: true }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    uniqueIndex("sessions_token_hash_unique").on(t.tokenHash),
    index("sessions_user_id_idx").on(t.userId),
    index("sessions_expires_at_idx").on(t.expiresAt),
  ],
);

/* ------------------------------------------------------------------ */
/* email_tokens                                                        */
/* ------------------------------------------------------------------ */

export const emailTokens = pgTable(
  "email_tokens",
  {
    id: id(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    type: emailTokenTypeEnum("type").notNull(),
    tokenHash: text("token_hash").notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    usedAt: timestamp("used_at", { withTimezone: true }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    uniqueIndex("email_tokens_token_hash_unique").on(t.tokenHash),
    index("email_tokens_user_type_idx").on(t.userId, t.type),
  ],
);

/* ------------------------------------------------------------------ */
/* pending_registrations (D-067)                                       */
/* ------------------------------------------------------------------ */

/**
 * A registration whose address has not been verified yet. The account only
 * comes into existence when the link in the verification e-mail is followed;
 * until then the form data sits here. The row is genuinely disposable, like
 * `email_tokens`: it is hard deleted once the account is created, a newer
 * submission for the same address supersedes it, and the purge job drops
 * expired ones.
 */
export const pendingRegistrations = pgTable(
  "pending_registrations",
  {
    id: id(),
    /** Always stored lowercase and trimmed, exactly like `users.email`. */
    email: text("email").notNull(),
    /** Argon2 hash; hashed once at submission so the expensive work is not repeated. */
    passwordHash: text("password_hash").notNull(),
    displayName: text("display_name").notNull(),
    birthDate: date("birth_date").notNull(),
    /** The KVKK notice version the applicant ticked at submission time. */
    kvkkConsentVersion: integer("kvkk_consent_version").notNull(),
    tokenHash: text("token_hash").notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    usedAt: timestamp("used_at", { withTimezone: true }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    uniqueIndex("pending_registrations_token_hash_unique").on(t.tokenHash),
    index("pending_registrations_email_idx").on(t.email),
    index("pending_registrations_expires_at_idx").on(t.expiresAt),
  ],
);

/* ------------------------------------------------------------------ */
/* login_challenges (two-factor step, D-048)                           */
/* ------------------------------------------------------------------ */

/**
 * A single-use ticket issued after the password half of a two-factor login.
 * Carries no secrets itself: only the peppered hash is stored, and the row
 * dies five minutes after it was issued.
 */
export const loginChallenges = pgTable(
  "login_challenges",
  {
    id: id(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    tokenHash: text("token_hash").notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    consumedAt: timestamp("consumed_at", { withTimezone: true }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    uniqueIndex("login_challenges_token_hash_unique").on(t.tokenHash),
    index("login_challenges_user_idx").on(t.userId),
    index("login_challenges_expires_at_idx").on(t.expiresAt),
  ],
);

/**
 * One-time recovery codes for the second factor (D-099): the way back in when
 * the phone with the authenticator app is lost. Only the peppered hash is
 * stored; the raw codes are shown once, when a set is generated.
 */
export const totpRecoveryCodes = pgTable(
  "totp_recovery_codes",
  {
    id: id(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    codeHash: text("code_hash").notNull(),
    usedAt: timestamp("used_at", { withTimezone: true }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    uniqueIndex("totp_recovery_codes_user_code_unique").on(t.userId, t.codeHash),
    index("totp_recovery_codes_user_idx").on(t.userId),
  ],
);

/* ------------------------------------------------------------------ */
/* writer_areas (managed by the admin panel, D-055)                    */
/* ------------------------------------------------------------------ */

/**
 * The writing areas a candidate picks from at registration. Managed from the
 * admin panel (D-055); the fixed code list from D-051 is now the seed set.
 * `users.writer_area` holds the area's name as free text, so a rename keeps
 * the users in step inside the same transaction.
 */
export const writerAreas = pgTable(
  "writer_areas",
  {
    id: id(),
    name: text("name").notNull(),
    /** How many approved writers the area may hold (D-052). */
    quota: integer("quota").notNull().default(3),
    isActive: boolean("is_active").notNull().default(true),
    /** Stable hand ordering for the public form and the admin list. */
    sortOrder: integer("sort_order").notNull().default(0),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    uniqueIndex("writer_areas_name_unique").on(t.name),
    index("writer_areas_active_sort_idx").on(t.isActive, t.sortOrder),
  ],
);

/* ------------------------------------------------------------------ */
/* editor_categories (editor area assignments, D-059)                  */
/* ------------------------------------------------------------------ */

/**
 * Which magazine areas an editor is responsible for. The area list is the same
 * `writer_areas` table (the 11 categories), but the rule here is the reverse
 * of the writer quota: one area belongs to exactly one editor (enforced by the
 * unique index on `area_id`), and an editor holds at most two slots (1 and 2,
 * enforced in the service — a unique index cannot count).
 *
 * A category editor reviews `in_review` articles of their own areas only; a
 * main editor (`users.is_main_editor`) reads every category and approves the
 * second review stage (D-059).
 */
export const editorCategories = pgTable(
  "editor_categories",
  {
    id: id(),
    editorId: uuid("editor_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    areaId: uuid("area_id")
      .notNull()
      .references(() => writerAreas.id, { onDelete: "restrict" }),
    /** 1 or 2; "1. alan" and "2. alan" as the product calls them. */
    slot: integer("slot").notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    // The requested unique constraint: a category can never be assigned twice
    uniqueIndex("editor_categories_area_unique").on(t.areaId),
    uniqueIndex("editor_categories_editor_slot_unique").on(t.editorId, t.slot),
    index("editor_categories_editor_idx").on(t.editorId),
  ],
);

/* ------------------------------------------------------------------ */
/* auth_attempts (rate limiting, D-007)                                */
/* ------------------------------------------------------------------ */

export const authAttempts = pgTable(
  "auth_attempts",
  {
    id: id(),
    scope: authScopeEnum("scope").notNull(),
    /** IP address or lowercased e-mail, depending on the scope. */
    identifier: text("identifier").notNull(),
    count: integer("count").notNull().default(0),
    /** Set while the bucket is locked out; requests are rejected until it passes. */
    lockedUntil: timestamp("locked_until", { withTimezone: true }),
    windowStartedAt: timestamp("window_started_at", { withTimezone: true }).notNull().defaultNow(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [uniqueIndex("auth_attempts_scope_identifier_unique").on(t.scope, t.identifier)],
);

/* ------------------------------------------------------------------ */
/* role_changes (append only, D-015)                                   */
/* ------------------------------------------------------------------ */

export const roleChanges = pgTable(
  "role_changes",
  {
    id: id(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),
    oldRole: roleEnum("old_role").notNull(),
    newRole: roleEnum("new_role").notNull(),
    changedBy: uuid("changed_by").references(() => users.id, { onDelete: "restrict" }),
    note: text("note"),
    createdAt: createdAt(),
  },
  (t) => [index("role_changes_user_idx").on(t.userId)],
);

/* ------------------------------------------------------------------ */
/* media                                                               */
/* ------------------------------------------------------------------ */

export const media = pgTable(
  "media",
  {
    id: id(),
    storageKey: text("storage_key").notNull(),
    mime: text("mime").notNull(),
    size: integer("size").notNull(),
    width: integer("width"),
    height: integer("height"),
    uploadedBy: uuid("uploaded_by").references(() => users.id, { onDelete: "set null" }),

    /** A media row without a license type can never be attached to an article. */
    licenseType: licenseTypeEnum("license_type"),
    licenseSource: text("license_source"),
    licenseEvidenceMediaId: uuid("license_evidence_media_id"),
    altText: text("alt_text"),

    createdAt: createdAt(),
    updatedAt: updatedAt(),
    deletedAt: deletedAt(),
  },
  (t) => [index("media_uploaded_by_idx").on(t.uploadedBy)],
);

/* ------------------------------------------------------------------ */
/* agreement_versions / agreement_acceptances                          */
/* ------------------------------------------------------------------ */

export const agreementVersions = pgTable(
  "agreement_versions",
  {
    id: id(),
    version: integer("version").notNull(),
    title: text("title").notNull(),
    bodyMarkdown: text("body_markdown").notNull(),
    /** sha256 of the exact body text that was published. */
    bodyHash: text("body_hash").notNull(),
    pdfMediaId: uuid("pdf_media_id").references(() => media.id, { onDelete: "set null" }),
    publishedAt: timestamp("published_at", { withTimezone: true }),
    publishedBy: uuid("published_by").references(() => users.id, { onDelete: "set null" }),
    isCurrent: boolean("is_current").notNull().default(false),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
    deletedAt: deletedAt(),
  },
  (t) => [
    uniqueIndex("agreement_versions_version_unique").on(t.version),
    // At most one current version at any time, enforced by the database
    uniqueIndex("agreement_versions_single_current").on(t.isCurrent).where(sql`${t.isCurrent}`),
  ],
);

export const agreementAcceptances = pgTable(
  "agreement_acceptances",
  {
    id: id(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),
    agreementVersionId: uuid("agreement_version_id")
      .notNull()
      .references(() => agreementVersions.id, { onDelete: "restrict" }),
    acceptedAt: timestamp("accepted_at", { withTimezone: true }).notNull().defaultNow(),
    ip: text("ip"),
    userAgent: text("user_agent"),
    /** Hash of the text actually shown to the user at acceptance time. */
    bodyHashAtAcceptance: text("body_hash_at_acceptance").notNull(),
    /**
     * The contract exactly as it was shown, placeholders filled (§4). This is
     * the evidence; the PDF is only a readable copy of it.
     */
    renderedMarkdown: text("rendered_markdown"),
    pdfMediaId: uuid("pdf_media_id").references(() => media.id, { onDelete: "set null" }),
    /** Filled in when a newer version is published; the row is never deleted. */
    supersededAt: timestamp("superseded_at", { withTimezone: true }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    uniqueIndex("agreement_acceptances_user_version_unique").on(t.userId, t.agreementVersionId),
  ],
);

/* ------------------------------------------------------------------ */
/* announcements                                                       */
/* ------------------------------------------------------------------ */

export const announcements = pgTable(
  "announcements",
  {
    id: id(),
    title: text("title").notNull(),
    bodyMarkdown: text("body_markdown").notNull(),
    audience: announcementAudienceEnum("audience").notNull(),
    severity: announcementSeverityEnum("severity").notNull().default("info"),
    requiresAcknowledgement: boolean("requires_acknowledgement").notNull().default(false),
    publishedAt: timestamp("published_at", { withTimezone: true }),
    publishedBy: uuid("published_by").references(() => users.id, { onDelete: "set null" }),
    pinned: boolean("pinned").notNull().default(false),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
    deletedAt: deletedAt(),
  },
  (t) => [index("announcements_published_at_idx").on(t.publishedAt)],
);

export const announcementReads = pgTable(
  "announcement_reads",
  {
    id: id(),
    announcementId: uuid("announcement_id")
      .notNull()
      .references(() => announcements.id, { onDelete: "cascade" }),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    readAt: timestamp("read_at", { withTimezone: true }).notNull().defaultNow(),
    acknowledgedAt: timestamp("acknowledged_at", { withTimezone: true }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [uniqueIndex("announcement_reads_unique").on(t.announcementId, t.userId)],
);

/* ------------------------------------------------------------------ */
/* issues                                                              */
/* ------------------------------------------------------------------ */

export const issues = pgTable(
  "issues",
  {
    id: id(),
    number: integer("number").notNull(),
    title: text("title").notNull(),
    theme: text("theme"),
    /** The paragraph the magazines design prints under an issue's name (D-148). */
    blurb: text("blurb"),
    coverMediaId: uuid("cover_media_id").references(() => media.id, { onDelete: "set null" }),
    /**
     * A working issue that only the admins may open (D-240). Narrower than
     * "the editorial team": the sample issue we develop the reader against is
     * not something an editor or a writer should stumble into, so the door in
     * `readIssuePages` asks for the admin panel, not the editor panel.
     */
    adminOnly: boolean("admin_only").notNull().default(false),
    status: issueStatusEnum("status").notNull().default("planning"),
    plannedPublishDate: date("planned_publish_date"),
    publishedAt: timestamp("published_at", { withTimezone: true }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
    deletedAt: deletedAt(),
  },
  (t) => [uniqueIndex("issues_number_unique").on(t.number).where(sql`${t.deletedAt} is null`)],
);

/**
 * The pages an issue is laid out from (D-234).
 *
 * A page is a layout plus the words and pictures that layout asks for, not a
 * file: the magazine is read as web pages, so the text stays selectable and
 * the pictures stay separate things. A page may instead point at an article
 * that already exists, and then it shows that article's own words — linking
 * one never changes the article or its status.
 *
 * Every field is optional on purpose: the shape of an issue is designed before
 * its contents exist, and an empty page still has to be worth looking at.
 */
export const issuePages = pgTable(
  "issue_pages",
  {
    id: id(),
    issueId: uuid("issue_id")
      .notNull()
      .references(() => issues.id, { onDelete: "cascade" }),
    /** Order within the issue, dense from 1; the service keeps it that way. */
    position: integer("position").notNull(),
    template: pageTemplateEnum("template").notNull(),

    /** What the contents page calls this page; falls back to the heading. */
    tocTitle: text("toc_title"),
    /** Kept out of the contents when the page is a divider or a picture. */
    inContents: boolean("in_contents").notNull().default(true),

    heading: text("heading"),
    /** The standfirst the design sets under a heading. */
    standfirst: text("standfirst"),
    byline: text("byline"),
    body: text("body"),

    imageMediaId: uuid("image_media_id").references(() => media.id, { onDelete: "set null" }),
    caption: text("caption"),

    /**
     * The designed page, as delivered (D-240). When this is set the page *is*
     * the picture: the reader shows it whole and puts the clickable areas on
     * top of it, and the template fields above are left alone.
     *
     * The natural size is kept so the reader can reserve the right shape
     * before the file arrives, and so a replacement whose proportions differ
     * can be flagged — the areas are stored in fractions of the picture, and
     * a different shape moves what they sit on.
     */
    imageWidth: integer("image_width"),
    imageHeight: integer("image_height"),
    /** What this page is called in the panel's list; never shown to a reader. */
    label: text("label"),
    /** The page's own alternative text, which beats the media row's. */
    imageAlt: text("image_alt"),
    /** Optional plain text of what the page shows, for a screen reader. */
    transcript: text("transcript"),

    /** An article this page shows instead of its own body; never modified by us. */
    articleId: uuid("article_id").references(() => articles.id, { onDelete: "set null" }),
    /** The area this page belongs to, by name, as `writer_areas` spells it. */
    section: text("section"),

    /** Optional interaction blocks, validated by `issuePageBlocksSchema`. */
    blocks: jsonb("blocks").notNull().default(sql`'[]'::jsonb`),

    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    index("issue_pages_issue_position_idx").on(t.issueId, t.position),
    uniqueIndex("issue_pages_issue_position_unique").on(t.issueId, t.position),
  ],
);

/**
 * A quiz an issue carries (D-240).
 *
 * The questions and the outcome bands are JSON because they are a shape, not a
 * relation: nothing ever queries "every option of every quiz", and keeping one
 * quiz in one row means the panel saves it in one write and can never leave
 * half of it behind. `src/lib/issue-quiz.ts` is the only thing that reads the
 * shape, and it drops whatever no longer parses instead of throwing.
 *
 * Nothing about who answered is stored: there is no score archive and no
 * leaderboard, so a reader can try a quiz without leaving a record anywhere.
 */
export const issueQuizzes = pgTable(
  "issue_quizzes",
  {
    id: id(),
    issueId: uuid("issue_id")
      .notNull()
      .references(() => issues.id, { onDelete: "cascade" }),
    kind: quizKindEnum("kind").notNull(),
    title: text("title").notNull(),
    intro: text("intro"),
    /** `[{ id, text, explanation, options: [{ id, text, correct, points }] }]` */
    questions: jsonb("questions").notNull().default(sql`'[]'::jsonb`),
    /** Scored quizzes only: `[{ id, title, body, min, max }]`. */
    outcomes: jsonb("outcomes").notNull().default(sql`'[]'::jsonb`),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [index("issue_quizzes_issue_idx").on(t.issueId)],
);

/**
 * A clickable area drawn on a page image (D-240).
 *
 * Position is stored as fractions of the picture (0..1), never as pixels: the
 * same rectangle then lands on the same part of the design whatever the
 * screen, the zoom or the rendered size. The padding around the picture is not
 * part of the picture, so the reader measures the image element itself.
 *
 * A jump points at a page id, never at a page number, so reordering an issue
 * cannot silently send a reader somewhere else.
 */
export const issuePageHotspots = pgTable(
  "issue_page_hotspots",
  {
    id: id(),
    pageId: uuid("page_id")
      .notNull()
      .references(() => issuePages.id, { onDelete: "cascade" }),
    /** Drawing order within the page; also the tab order for a keyboard. */
    position: integer("position").notNull(),

    kind: hotspotKindEnum("kind").notNull(),
    /** What the panel calls it in the list beside the picture. */
    name: text("name"),
    /** What a screen reader announces; falls back to the name. */
    ariaLabel: text("aria_label"),
    /** Whether a reader sees a hint over the area, or only finds it by trying. */
    showMarker: boolean("show_marker").notNull().default(false),

    x: doublePrecision("x").notNull(),
    y: doublePrecision("y").notNull(),
    w: doublePrecision("w").notNull(),
    h: doublePrecision("h").notNull(),

    /** `link`: where it goes, and whether it leaves the magazine. */
    url: text("url"),
    openInNewTab: boolean("open_in_new_tab").notNull().default(true),

    /** `page`: the page to jump to, by id. */
    targetPageId: uuid("target_page_id").references((): AnyPgColumn => issuePages.id, {
      onDelete: "set null",
    }),

    /** `info`: the little window that opens over the page. */
    infoTitle: text("info_title"),
    infoBody: text("info_body"),
    infoMediaId: uuid("info_media_id").references(() => media.id, { onDelete: "set null" }),

    /** `quiz`: which quiz opens. Several areas may point at the same one. */
    quizId: uuid("quiz_id").references(() => issueQuizzes.id, { onDelete: "set null" }),

    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [index("issue_page_hotspots_page_idx").on(t.pageId, t.position)],
);

export type IssuePageHotspot = typeof issuePageHotspots.$inferSelect;
export type IssueQuiz = typeof issueQuizzes.$inferSelect;

/* ------------------------------------------------------------------ */
/* articles                                                            */
/* ------------------------------------------------------------------ */

export const articles = pgTable(
  "articles",
  {
    id: id(),
    issueId: uuid("issue_id").references(() => issues.id, { onDelete: "set null" }),
    title: text("title").notNull(),
    slug: text("slug").notNull(),
    summary: text("summary"),
    /** Pasted in by an editor; there is no writer-facing submission flow in this phase. */
    bodyMarkdown: text("body_markdown").notNull().default(""),

    authorId: uuid("author_id").references(() => users.id, { onDelete: "restrict" }),

    // `subcategory` ("alt köşe") and `tags` were dropped in D-082
    category: text("category"),

    status: articleStatusEnum("status").notNull().default("draft"),

    dueDate: date("due_date"),
    scheduledAt: timestamp("scheduled_at", { withTimezone: true }),
    publishedAt: timestamp("published_at", { withTimezone: true }),
    withdrawnAt: timestamp("withdrawn_at", { withTimezone: true }),
    withdrawnReason: text("withdrawn_reason"),

    orderInIssue: integer("order_in_issue"),

    plagiarismCheckStatus: plagiarismStatusEnum("plagiarism_check_status")
      .notNull()
      .default("not_run"),
    plagiarismNote: text("plagiarism_note"),

    createdAt: createdAt(),
    updatedAt: updatedAt(),
    deletedAt: deletedAt(),
  },
  (t) => [
    uniqueIndex("articles_slug_unique").on(t.slug).where(sql`${t.deletedAt} is null`),
    index("articles_status_idx").on(t.status),
    index("articles_issue_idx").on(t.issueId),
    index("articles_author_idx").on(t.authorId),
    index("articles_scheduled_at_idx").on(t.scheduledAt),
  ],
);

export const articleVersions = pgTable(
  "article_versions",
  {
    id: id(),
    articleId: uuid("article_id")
      .notNull()
      .references(() => articles.id, { onDelete: "cascade" }),
    version: integer("version").notNull(),
    bodyMarkdown: text("body_markdown").notNull(),
    changedBy: uuid("changed_by").references(() => users.id, { onDelete: "set null" }),
    changeNote: text("change_note"),
    /** A content change revokes the work approval; a correction keeps it (§7.5). */
    changeKind: changeKindEnum("change_kind").notNull().default("correction"),
    /** Marks the snapshot taken at the moment the article went public. */
    isPublishedSnapshot: boolean("is_published_snapshot").notNull().default(false),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [uniqueIndex("article_versions_article_version_unique").on(t.articleId, t.version)],
);

export const articleComments = pgTable(
  "article_comments",
  {
    id: id(),
    articleId: uuid("article_id")
      .notNull()
      .references(() => articles.id, { onDelete: "cascade" }),
    authorId: uuid("author_id").references(() => users.id, { onDelete: "set null" }),
    body: text("body").notNull(),
    resolvedAt: timestamp("resolved_at", { withTimezone: true }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
    deletedAt: deletedAt(),
  },
  (t) => [index("article_comments_article_idx").on(t.articleId)],
);

/** Which media a given article uses; license completeness is checked over this join. */
export const articleMedia = pgTable(
  "article_media",
  {
    id: id(),
    articleId: uuid("article_id")
      .notNull()
      .references(() => articles.id, { onDelete: "cascade" }),
    mediaId: uuid("media_id")
      .notNull()
      .references(() => media.id, { onDelete: "restrict" }),
    role: text("role").notNull().default("inline"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [uniqueIndex("article_media_unique").on(t.articleId, t.mediaId)],
);

/* ------------------------------------------------------------------ */
/* rights_grants                                                       */
/* ------------------------------------------------------------------ */

export const rightsGrants = pgTable(
  "rights_grants",
  {
    id: id(),
    articleId: uuid("article_id")
      .notNull()
      .references(() => articles.id, { onDelete: "cascade" }),
    grantorId: uuid("grantor_id")
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),

    /** The contract version whose article 4 fixes this licence's scope (§7.1). */
    agreementVersionId: uuid("agreement_version_id").references(() => agreementVersions.id, {
      onDelete: "restrict",
    }),
    bylineChoice: bylineChoiceEnum("byline_choice"),

    grantType: grantTypeEnum("grant_type").notNull(),

    // FSEK requires each economic right to be listed one by one (art. 52)
    rightAdaptation: boolean("right_adaptation").notNull().default(false), // m.21 işleme
    rightReproduction: boolean("right_reproduction").notNull().default(false), // m.22 çoğaltma
    rightDistribution: boolean("right_distribution").notNull().default(false), // m.23 yayma
    rightCommunicationToPublic: boolean("right_communication_to_public").notNull().default(false), // m.25 umuma iletim

    channels: text("channels")
      .array()
      .notNull()
      .default(sql`'{}'::text[]`),
    exclusivityMonths: integer("exclusivity_months"),
    territory: text("territory").notNull().default("worldwide"),
    consideration: considerationEnum("consideration").notNull().default("none"),
    commercialUseIncluded: boolean("commercial_use_included").notNull().default(false),

    /** sha256 of the work's body as it stood when the licence was declared. */
    formTextHash: text("form_text_hash").notNull(),
    /**
     * The body itself, kept beside its hash (D-238). The hash proves nothing
     * changed; this is what was actually licensed, so it has to be readable
     * years later without reconstructing it from the version history.
     */
    acceptedBodyMarkdown: text("accepted_body_markdown"),
    /** Which `article_versions` number the declaration was made against. */
    acceptedVersion: integer("accepted_version"),
    formPdfMediaId: uuid("form_pdf_media_id").references(() => media.id, { onDelete: "set null" }),

    status: grantStatusEnum("status").notNull().default("pending"),
    signedAt: timestamp("signed_at", { withTimezone: true }),
    signedIp: text("signed_ip"),
    signedUserAgent: text("signed_user_agent"),
    declinedAt: timestamp("declined_at", { withTimezone: true }),
    declinedReason: text("declined_reason"),
    revokedAt: timestamp("revoked_at", { withTimezone: true }),
    revokedBy: uuid("revoked_by").references(() => users.id, { onDelete: "set null" }),
    /** Set when the writer was last nudged, so reminders do not repeat daily. */
    reminderSentAt: timestamp("reminder_sent_at", { withTimezone: true }),

    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    // One live approval per article; revoked and declined ones stay as history
    uniqueIndex("rights_grants_article_active_unique")
      .on(t.articleId)
      .where(sql`${t.status} in ('pending', 'signed')`),
    index("rights_grants_grantor_idx").on(t.grantorId),
    index("rights_grants_status_idx").on(t.status),
  ],
);

/* ------------------------------------------------------------------ */
/* kvkk_versions                                                       */
/* ------------------------------------------------------------------ */

export const kvkkVersions = pgTable(
  "kvkk_versions",
  {
    id: id(),
    version: integer("version").notNull(),
    title: text("title").notNull(),
    bodyMarkdown: text("body_markdown").notNull(),
    bodyHash: text("body_hash").notNull(),
    publishedAt: timestamp("published_at", { withTimezone: true }),
    publishedBy: uuid("published_by").references(() => users.id, { onDelete: "set null" }),
    isCurrent: boolean("is_current").notNull().default(false),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    uniqueIndex("kvkk_versions_version_unique").on(t.version),
    uniqueIndex("kvkk_versions_single_current").on(t.isCurrent).where(sql`${t.isCurrent}`),
  ],
);

/* ------------------------------------------------------------------ */
/* site_settings (publisher details for the contract, §3)              */

/* ------------------------------------------------------------------ */

/**
 * Values the contract template needs but the database cannot infer: who the
 * publishing partners are, the notification address, the jurisdiction. Only an
 * admin edits them and every change lands in the audit log.
 */
export const siteSettings = pgTable("site_settings", {
  key: text("key").primaryKey(),
  value: text("value").notNull(),
  updatedBy: uuid("updated_by").references(() => users.id, { onDelete: "set null" }),
  createdAt: createdAt(),
  updatedAt: updatedAt(),
});

/* ------------------------------------------------------------------ */
/* notifications (in-panel, D-008)                                     */
/* ------------------------------------------------------------------ */

export const notifications = pgTable(
  "notifications",
  {
    id: id(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    kind: text("kind").notNull(),
    title: text("title").notNull(),
    body: text("body"),
    href: text("href"),
    readAt: timestamp("read_at", { withTimezone: true }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [index("notifications_user_idx").on(t.userId, t.readAt)],
);

/* ------------------------------------------------------------------ */
/* community (blog comments, chat, banned words)                       */
/* ------------------------------------------------------------------ */

/**
 * The moderation blacklist (module 4). Words are stored normalized (lowercase,
 * Turkish locale) and matched case-insensitively as substrings, so suffixed
 * forms are covered too. Removal is a soft delete so an admin can restore.
 */
export const bannedWords = pgTable(
  "banned_words",
  {
    id: id(),
    word: text("word").notNull(),
    createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
    deletedAt: deletedAt(),
  },
  (t) => [
    // A live word is unique; soft-deleted ones stay as history
    uniqueIndex("banned_words_word_unique").on(t.word).where(sql`${t.deletedAt} is null`),
  ],
);

/** A reader's comment on a published magazine article. */
export const communityComments = pgTable(
  "community_comments",
  {
    id: id(),
    articleId: uuid("article_id")
      .notNull()
      .references(() => articles.id, { onDelete: "cascade" }),
    authorId: uuid("author_id").references(() => users.id, { onDelete: "set null" }),
    /** The comment with banned words already masked (module 4). */
    body: text("body").notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
    deletedAt: deletedAt(),
  },
  (t) => [
    index("community_comments_article_idx").on(t.articleId, t.createdAt),
  ],
);

/** A message in the community chat; an optional quote references another one. */
export const communityMessages = pgTable(
  "community_messages",
  {
    id: id(),
    authorId: uuid("author_id").references(() => users.id, { onDelete: "set null" }),
    body: text("body").notNull(),
    // Self reference: the explicit return type breaks the circular inference
    quotedMessageId: uuid("quoted_message_id").references(
      (): AnyPgColumn => communityMessages.id,
      { onDelete: "set null" },
    ),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
    deletedAt: deletedAt(),
  },
  (t) => [index("community_messages_created_idx").on(t.createdAt)],
);

/**
 * The 5651 m. 5 traffic record of every piece of user content (D-088).
 *
 * Kept apart from `audit_log` on purpose: the audit trail lives for ten years
 * and a trigger forbids deleting from it, while a traffic record has a
 * statutory one-year life and is pruned once that year is over.
 */
export const trafficLogs = pgTable(
  "traffic_logs",
  {
    id: id(),
    // The record must outlive an anonymised account, so the link only loosens
    userId: uuid("user_id").references(() => users.id, { onDelete: "set null" }),
    action: text("action").notNull(),
    entityType: text("entity_type").notNull(),
    entityId: uuid("entity_id"),
    ip: text("ip"),
    userAgent: text("user_agent"),
    createdAt: createdAt(),
  },
  (t) => [
    index("traffic_logs_created_idx").on(t.createdAt),
    index("traffic_logs_entity_idx").on(t.entityType, t.entityId),
  ],
);

/* ------------------------------------------------------------------ */
/* social graph (D-089)                                                */
/* ------------------------------------------------------------------ */

/*
 * Follows, blocks and bookmarks break the soft-delete convention on purpose:
 * they carry no content, and keeping a retracted follow or a lifted block
 * would store a piece of someone's social graph they took back (KVKK data
 * minimisation). Undoing one deletes the row.
 */

export const follows = pgTable(
  "follows",
  {
    id: id(),
    followerId: uuid("follower_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    followeeId: uuid("followee_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    createdAt: createdAt(),
  },
  (t) => [
    uniqueIndex("follows_pair_unique").on(t.followerId, t.followeeId),
    index("follows_followee_idx").on(t.followeeId),
  ],
);

/** A block works both ways: neither side can follow, message or reach the other. */
export const userBlocks = pgTable(
  "user_blocks",
  {
    id: id(),
    blockerId: uuid("blocker_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    blockedId: uuid("blocked_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    createdAt: createdAt(),
  },
  (t) => [
    uniqueIndex("user_blocks_pair_unique").on(t.blockerId, t.blockedId),
    index("user_blocks_blocked_idx").on(t.blockedId),
  ],
);

/* ------------------------------------------------------------------ */
/* communities (D-093)                                                 */
/* ------------------------------------------------------------------ */

/** A topic group. Only an admin opens or archives one; members join and post. */
export const communities = pgTable(
  "communities",
  {
    id: id(),
    slug: text("slug").notNull(),
    name: text("name").notNull(),
    description: text("description"),
    createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }),
    /** An archived community stays readable but takes no new members or posts. */
    archivedAt: timestamp("archived_at", { withTimezone: true }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [uniqueIndex("communities_slug_unique").on(t.slug)],
);

/** Membership is a toggle and follows the hard-delete rule of D-089. */
export const communityMemberships = pgTable(
  "community_memberships",
  {
    id: id(),
    communityId: uuid("community_id")
      .notNull()
      .references(() => communities.id, { onDelete: "cascade" }),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    createdAt: createdAt(),
  },
  (t) => [
    uniqueIndex("community_memberships_pair_unique").on(t.communityId, t.userId),
    index("community_memberships_user_idx").on(t.userId),
  ],
);

/* ------------------------------------------------------------------ */
/* member posts (D-090)                                                */
/* ------------------------------------------------------------------ */

/** A member's short post; a reply points at the post it answers. */
export const posts = pgTable(
  "posts",
  {
    id: id(),
    authorId: uuid("author_id").references(() => users.id, { onDelete: "set null" }),
    /** Stored with banned words already masked (D-040). */
    body: text("body").notNull(),
    replyToId: uuid("reply_to_id").references((): AnyPgColumn => posts.id, {
      onDelete: "set null",
    }),
    /** The community the post was shared in (D-093); null for a plain post. */
    communityId: uuid("community_id").references(() => communities.id, { onDelete: "set null" }),
    /** The moderator who took it down; null when the author deleted it. */
    removedBy: uuid("removed_by").references(() => users.id, { onDelete: "set null" }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
    deletedAt: deletedAt(),
  },
  (t) => [
    index("posts_author_idx").on(t.authorId, t.createdAt),
    index("posts_reply_to_idx").on(t.replyToId, t.createdAt),
    index("posts_created_idx").on(t.createdAt),
    index("posts_community_idx").on(t.communityId, t.createdAt),
  ],
);

/** Likes and reposts are toggles and follow the hard-delete rule of D-089. */
export const postLikes = pgTable(
  "post_likes",
  {
    id: id(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    postId: uuid("post_id")
      .notNull()
      .references(() => posts.id, { onDelete: "cascade" }),
    createdAt: createdAt(),
  },
  (t) => [
    uniqueIndex("post_likes_pair_unique").on(t.userId, t.postId),
    index("post_likes_post_idx").on(t.postId),
  ],
);

export const postReposts = pgTable(
  "post_reposts",
  {
    id: id(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    postId: uuid("post_id")
      .notNull()
      .references(() => posts.id, { onDelete: "cascade" }),
    createdAt: createdAt(),
  },
  (t) => [
    uniqueIndex("post_reposts_pair_unique").on(t.userId, t.postId),
    index("post_reposts_post_idx").on(t.postId),
  ],
);

/** A reader's private reading list: an article or a post, never both. */
export const bookmarks = pgTable(
  "bookmarks",
  {
    id: id(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    articleId: uuid("article_id").references(() => articles.id, { onDelete: "cascade" }),
    postId: uuid("post_id").references(() => posts.id, { onDelete: "cascade" }),
    createdAt: createdAt(),
  },
  (t) => [
    uniqueIndex("bookmarks_user_article_unique").on(t.userId, t.articleId),
    uniqueIndex("bookmarks_user_post_unique").on(t.userId, t.postId),
    check("bookmarks_one_target", sql`num_nonnulls(${t.articleId}, ${t.postId}) = 1`),
  ],
);

/* ------------------------------------------------------------------ */
/* content reports (D-090)                                             */
/* ------------------------------------------------------------------ */

/** Every kind of user content a member can report, including later modules. */
export const reportTargetEnum = pgEnum("report_target", [
  "post",
  "comment",
  "direct_message",
  "anon_message",
  "member",
]);

export const reportCategoryEnum = pgEnum("report_category", [
  "harassment",
  "hate",
  "personal_data",
  "copyright",
  "spam",
  "illegal",
  "impersonation",
  "other",
]);

export const reportStatusEnum = pgEnum("report_status", ["open", "removed", "dismissed"]);

/**
 * A member's report about a piece of content (5651 m. 9 notice path). The
 * snapshot keeps the text as it was reported, so the moderator judges what the
 * reporter saw even if the author deletes or the content is private.
 */
export const contentReports = pgTable(
  "content_reports",
  {
    id: id(),
    reporterId: uuid("reporter_id").references(() => users.id, { onDelete: "set null" }),
    targetType: reportTargetEnum("target_type").notNull(),
    targetId: uuid("target_id").notNull(),
    targetUserId: uuid("target_user_id").references(() => users.id, { onDelete: "set null" }),
    category: reportCategoryEnum("category").notNull(),
    reason: text("reason"),
    snapshot: text("snapshot").notNull(),
    status: reportStatusEnum("status").notNull().default("open"),
    resolvedBy: uuid("resolved_by").references(() => users.id, { onDelete: "set null" }),
    resolvedAt: timestamp("resolved_at", { withTimezone: true }),
    resolutionNote: text("resolution_note"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    index("content_reports_status_idx").on(t.status, t.createdAt),
    index("content_reports_target_idx").on(t.targetType, t.targetId),
  ],
);

/* ------------------------------------------------------------------ */
/* private messages (D-091)                                            */
/* ------------------------------------------------------------------ */

/**
 * A private conversation between exactly two members. The pair is stored in
 * order (`member_a_id` < `member_b_id`), so it has one row whoever wrote first.
 */
export const conversations = pgTable(
  "conversations",
  {
    id: id(),
    memberAId: uuid("member_a_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    memberBId: uuid("member_b_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    lastMessageAt: timestamp("last_message_at", { withTimezone: true }).notNull().defaultNow(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    uniqueIndex("conversations_pair_unique").on(t.memberAId, t.memberBId),
    index("conversations_member_b_idx").on(t.memberBId),
    check("conversations_ordered_pair", sql`${t.memberAId} < ${t.memberBId}`),
  ],
);

/** Each member's own view of a conversation: what they read and what they cleared. */
export const conversationStates = pgTable(
  "conversation_states",
  {
    id: id(),
    conversationId: uuid("conversation_id")
      .notNull()
      .references(() => conversations.id, { onDelete: "cascade" }),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    lastReadAt: timestamp("last_read_at", { withTimezone: true }),
    /** "Delete conversation" hides everything before this moment, for this member only. */
    clearedAt: timestamp("cleared_at", { withTimezone: true }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [uniqueIndex("conversation_states_pair_unique").on(t.conversationId, t.userId)],
);

export const directMessages = pgTable(
  "direct_messages",
  {
    id: id(),
    conversationId: uuid("conversation_id")
      .notNull()
      .references(() => conversations.id, { onDelete: "cascade" }),
    senderId: uuid("sender_id").references(() => users.id, { onDelete: "set null" }),
    /** Stored with banned words already masked (D-040). */
    body: text("body").notNull(),
    /** The moderator who removed it after a report; null when gone with the account. */
    removedBy: uuid("removed_by").references(() => users.id, { onDelete: "set null" }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
    deletedAt: deletedAt(),
  },
  (t) => [index("direct_messages_conversation_idx").on(t.conversationId, t.createdAt)],
);

/* ------------------------------------------------------------------ */
/* anonymous box (D-092, D-185)                                        */
/* ------------------------------------------------------------------ */

/**
 * A message left without the sender's name. Since D-185 the box is the
 * magazine's: a message with no recipient goes to the admins, for the
 * "Eğlence & Dedikodu" section. Rows with a recipient are left from the member
 * boxes of D-092, which closed. Anonymous to the reader only: the sender is
 * stored, because the magazine must be able to answer for it (5651 m. 5).
 */
export const anonMessages = pgTable(
  "anon_messages",
  {
    id: id(),
    /** Null for the magazine's box (D-185); a member for the old member boxes. */
    recipientId: uuid("recipient_id").references(() => users.id, { onDelete: "cascade" }),
    senderId: uuid("sender_id").references(() => users.id, { onDelete: "set null" }),
    /** Stored with banned words already masked (D-040). */
    body: text("body").notNull(),
    readAt: timestamp("read_at", { withTimezone: true }),
    /** The recipient deleted it from their box. */
    hiddenAt: timestamp("hidden_at", { withTimezone: true }),
    removedBy: uuid("removed_by").references(() => users.id, { onDelete: "set null" }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
    deletedAt: deletedAt(),
  },
  (t) => [
    index("anon_messages_recipient_idx").on(t.recipientId, t.createdAt),
    index("anon_messages_sender_idx").on(t.senderId, t.createdAt),
  ],
);

/**
 * A sender the recipient silenced without learning who it is. Not a block: a
 * block shows on the blocked person's profile and would give the name away.
 */
export const anonMutes = pgTable(
  "anon_mutes",
  {
    id: id(),
    recipientId: uuid("recipient_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    senderId: uuid("sender_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    createdAt: createdAt(),
  },
  (t) => [uniqueIndex("anon_mutes_pair_unique").on(t.recipientId, t.senderId)],
);

/* ------------------------------------------------------------------ */
/* team_avatars (D-194)                                                */
/* ------------------------------------------------------------------ */

/**
 * A team member's illustrated avatar: the chosen parts and the PNG drawn from
 * them. One per account; saving again replaces it.
 *
 * Deleted for real, not soft deleted: the avatar is the member's own optional
 * creation, nothing refers to it, and "Avatarımı sil" should leave nothing
 * behind (KVKK). The audit log keeps that it existed.
 */
export const teamAvatars = pgTable(
  "team_avatars",
  {
    id: id(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    /** As the member wants it credited on the team page; not the account name. */
    displayName: text("display_name").notNull(),
    teamRole: text("team_role").notNull(),
    /** Only catalogue ids (`src/lib/avatar/registry.ts`), so the builder can reopen it. */
    config: jsonb("config").notNull(),
    configVersion: integer("config_version").notNull(),
    /** The transparent PNG in object storage; regenerated from `config` if it goes missing. */
    pngStorageKey: text("png_storage_key"),

    /* The team form (D-226). Null until the member fills it in; it is asked
       for separately from the avatar and is not required to keep one. */

    /** A line of their own for the team page, at most 55 characters. */
    motto: text("motto"),
    /**
     * How they want to be named on the team page. This is NOT the article
     * byline: that one is signed per work on `rights_grants.byline_choice`
     * (FSEK), and neither may be read for the other.
     */
    teamByline: bylineChoiceEnum("team_byline"),
    zodiac: zodiacEnum("zodiac"),
    /** When the form was last answered; null means it never was. */
    teamFormAt: timestamp("team_form_at", { withTimezone: true }),

    /**
     * The admin's own tick: they have made this member's post (D-232). It is a
     * time rather than a flag so that a later `updated_at` tells us the member
     * changed the avatar after the tick, and the card can come back up marked
     * as changed. Nobody but the admin sees or sets it.
     */
    processedAt: timestamp("processed_at", { withTimezone: true }),

    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [uniqueIndex("team_avatars_user_unique").on(t.userId)],
);

/* ------------------------------------------------------------------ */
/* audit_log (append only, D-015)                                      */
/* ------------------------------------------------------------------ */

export const auditLog = pgTable(
  "audit_log",
  {
    id: id(),
    /** Null for actions performed by scheduled jobs rather than a person. */
    actorId: uuid("actor_id").references(() => users.id, { onDelete: "set null" }),
    action: text("action").notNull(),
    entityType: text("entity_type").notNull(),
    entityId: uuid("entity_id"),
    before: jsonb("before"),
    after: jsonb("after"),
    ip: text("ip"),
    createdAt: createdAt(),
  },
  (t) => [
    index("audit_log_entity_idx").on(t.entityType, t.entityId),
    index("audit_log_created_at_idx").on(t.createdAt),
    index("audit_log_actor_idx").on(t.actorId),
  ],
);

/* ------------------------------------------------------------------ */
/* Inferred types                                                      */
/* ------------------------------------------------------------------ */

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
export type Session = typeof sessions.$inferSelect;
export type Article = typeof articles.$inferSelect;
export type Issue = typeof issues.$inferSelect;
export type IssuePage = typeof issuePages.$inferSelect;
export type RightsGrant = typeof rightsGrants.$inferSelect;
export type WriterApplication = typeof writerApplications.$inferSelect;
export type MediaRow = typeof media.$inferSelect;
export type CommunityComment = typeof communityComments.$inferSelect;
export type CommunityMessage = typeof communityMessages.$inferSelect;
export type BannedWord = typeof bannedWords.$inferSelect;
export type AgreementVersion = typeof agreementVersions.$inferSelect;
export type Announcement = typeof announcements.$inferSelect;
export type WriterArea = typeof writerAreas.$inferSelect;
export type EditorCategory = typeof editorCategories.$inferSelect;
export type AnnouncementSeverity = (typeof announcementSeverityEnum.enumValues)[number];
export type Role = (typeof roleEnum.enumValues)[number];
export type ArticleStatus = (typeof articleStatusEnum.enumValues)[number];
export type WriterStatus = (typeof writerStatusEnum.enumValues)[number];
export type EditorStatus = (typeof editorStatusEnum.enumValues)[number];
export type GrantStatus = (typeof grantStatusEnum.enumValues)[number];
export type WriterApplicationStatus = (typeof writerApplicationStatusEnum.enumValues)[number];
export type LicenseType = (typeof licenseTypeEnum.enumValues)[number];
export type Post = typeof posts.$inferSelect;
export type ContentReport = typeof contentReports.$inferSelect;
export type ReportTarget = (typeof reportTargetEnum.enumValues)[number];
export type ReportCategory = (typeof reportCategoryEnum.enumValues)[number];
export type ReportStatus = (typeof reportStatusEnum.enumValues)[number];
export type DmPolicy = (typeof dmPolicyEnum.enumValues)[number];
export type TeamAvatar = typeof teamAvatars.$inferSelect;
